source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'erubis'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'
gem 'unicorn'

group :development do
  gem 'foreman'
  gem 'rack-lineprof'
end
